### ISSUE TITLE
boxShowOut argument of newSparkPlot seems not to function

### ISSUE THREAD

**Issue by pm321** [alexkowa/sparkTable#19] opened 2017-05-11 15:18 UTC
boxShowOut is a function for newSParkBox - 'logical vector specifying if outliers should be displayed in spark boxplots'

This argument is not described in setParameter and there seems to be no guidance on how the argument should be used in the package documentation.

I would have expected the argument to work like this:
  
`sparkbox <- newSparkBox(values = rlnorm(100), boxShowOut = FALSE)
`

or possibly:

```
sparkbox <- newSparkBox(values = rlnorm(100))
sparkbox <- setParameter(sparkbox, FALSE, type = "showOut")
plot(sparkbox)

```
Neither case works. I get the following error message:

```
Error in (function (cl, name, valueClass)  : 
‘boxShowOut’ is not a slot in class “sparkbox”

```          
My workround is to use the boxOutCol argument to make the outlier colour the same as the box backgound colour. Using the boxShowOut would be more correct.

**Comment by molfe797** [comment] 2017-09-28 18:31
I'm still getting the same error. Has a fix been found?

**Comment by bernhard-da** [comment] 2017-09-28 19:32
hi @molfe797 and @pm321 

thx for reporting this. could you please test, if the issue is resolved after the latest commit? you should be able to do something like

```
sparkbox <- newSparkBox(values = rlnorm(100), boxShowOut=FALSE)
plot(sparkbox)
```
and get/change this parameter using
```
sparkbox <- setParameter(sparkbox, FALSE, type="boxShowOut")
getParameter(sparkbox,  type="boxShowOut")
```

**Comment by molfe797** [comment] 2017-09-29 14:56
Using your example, I'm still getting the error message:

![image](https://user-images.githubusercontent.com/19910999/31021742-b61afb82-a504-11e7-86f9-c117de22fac3.png)

**Comment by bernhard-da** [comment] 2017-09-30 09:23
hi, thx for your feedback.

i get
```
> "boxShowOut" %in% slotNames(newSparkBox())
[1] TRUE
```
if you have this, the remaining code should work too. did you do a new install (e.g using `devtools::install_github("alexkowa/sparkTable")`?

**Comment by molfe797** [comment] 2017-10-03 16:38
@bernhard-da  I did not install the new version off git (just the one off Cran).

I downloaded the new library. Restarted R. I was able to set the boxShowOut t=slow to FALSE.

However, the output did not change. I attached one of the exported sparkBox. The code I used:

```
a <- newSparkBox()
a <- setParameter(a, FALSE, type="boxShowOut")
a<- setParameter(a, c("black", "lightblue"), type="boxCol")
```

[Use_Plots2-23.pdf](https://github.com/alexkowa/sparkTable/files/1353066/Use_Plots2-23.pdf)

**Comment by bernhard-da** [comment] 2017-10-03 16:51
hi @pm321 strange, i just tested and got with the following code
```
library(sparkTable)
a <- newSparkBox()
a <- setParameter(a, FALSE, type="boxShowOut")
a <- setParameter(a, c("black", "lightblue"), type="boxCol")
export(a, outputType="pdf", filename="myBox")
```

the following output: [myBox.pdf](https://github.com/alexkowa/sparkTable/files/1353172/myBox.pdf)

which is what I expected to get (also because you changed default colors).

do you have an up-to date R-installation?

**Comment by molfe797** [comment] 2017-10-04 15:50
I am using version 1.3.2 for sparkTable.

When I run the same code as you @pm321 , I get a boxplot with no outliers: 
![image](https://user-images.githubusercontent.com/19910999/31185436-f2390d68-a8f9-11e7-804e-77750102050b.png)

But, when I run it withing the export code, I still get outliers: 
`  # Box plot of duration
a <- newSparkBox()
a <- setParameter(a, FALSE, type="boxShowOut")
a <- setParameter(a, c("black", "lightblue"), type="boxCol")

# Historgram of Usage Type
b <-newSparkHist () 
b <- setParameter(b, .1, type="barSpacingPerc")
b <- setParameter(b, .5, type="width")
b <-  setParameter(b, c("green","red",NA), type="barCol")

content<-list(
  function(x) { NROW(x) }, # number of trips
  a, # box plot of duration
  function(x) {round(mean(x),2)}, # Average duration
  b
)

vars<-c("Part","Duration","Duration","Part")

names(content) <- c("Total Usage", "Mean Duration", "Duration", "Starting v Ending" )

use <- newSparkTable(dataObj = xx1, tableContent = content, varType = vars)

export(use, outputType = "tex", filename = "Use_Plots",graphNames = "Use_Plots")

`
![image](https://user-images.githubusercontent.com/19910999/31185410-dd11e450-a8f9-11e7-9b76-b1cfdbd63b78.png)

(Ignore the historgram. Still need to work out the kinks on that one too.

**Comment by bernhard-da** [comment] 2017-10-04 17:04
hi @molfe797 

thx for trying this out. unfortunately, i can't reproduce your code because I don't know what `xx1` is. could you please provide a reproducable example?

**Comment by molfe797** [comment] 2017-10-04 17:41
I included a subset of my data (original has 30 stations) and my code.

[Test for Spark.zip](https://github.com/alexkowa/sparkTable/files/1356818/Test.for.Spark.zip)

**Comment by bernhard-da** [comment] 2017-10-04 18:12
thx @molfe797 for the testdata. I think I found the problem. Could you please also check?

**Comment by molfe797** [comment] 2017-10-04 18:37
I reinstalled the package. With the same code and data, I get:  
![image](https://user-images.githubusercontent.com/19910999/31193172-62caecf6-a911-11e7-8280-53cafe56d189.png)

There is still the space for the outliers.

**Comment by bernhard-da** [comment] 2017-10-04 18:59
well, option `boxShowOut` really just "removes" the outliers from the boxplot. having a look at your data (eg. for Duration in Braddock Rd Metro), it seems that the resulting graph is due to the structure of your data as the "normal" boxplot just looks the same...

```
dat <- read.csv("Test_Data.csv")
boxplot(dat[dat$Station=="Braddock Rd Metro","Duration"])
```

![bp](https://user-images.githubusercontent.com/5228437/31194239-d36bb906-a946-11e7-8368-f41909ecda08.png)

**Comment by molfe797** [comment] 2017-10-04 20:14
Is there a way that would set the outline box? I had assumed that this is what the boxShowOut would have done based on the description.

```
dat <- read.csv("Test_Data.csv")
boxplot(dat[dat$Station=="Braddock Rd Metro","Duration"],outline = FALSE)

```
,outline = FALSE)
![image](https://user-images.githubusercontent.com/19910999/31197319-ae33ffa4-a91e-11e7-81af-9db9711e4248.png)

**Comment by molfe797** [comment] 2017-10-05 18:20
I might be wrong here, but this is where the code can be changed to allow for this?

https://github.com/alexkowa/sparkTable/blob/1351b84f3eb3aea73894091625531691fe8a084b/R/methods.r#L1064

**Comment by molfe797** [comment] 2017-10-05 18:27
Lines 1065-1071 in the methods.r file seem to  be where this would added. 

`geom_boxplot(outlier.shape=NA)`

**Comment by molfe797** [comment] 2017-10-05 18:51
Line 1070 seems the spot to do this.

https://github.com/alexkowa/sparkTable/blob/1351b84f3eb3aea73894091625531691fe8a084b/R/methods.r#L1070

In my test data, the current code you have would produce this:
![image](https://user-images.githubusercontent.com/19910999/31246757-6d1829f0-a9dc-11e7-8ac6-b604101b0dce.png)

But, by added limits to the code

`p <- ggplot(test, aes(factor(Station), Duration))
p + geom_boxplot(outlier.shape=NA) + scale_y_continuous(limits=c(quantile(test$Duration, 0.1),quantile(test$Duration, 0.9)),expand=c(0,0.02))`

the output looks like this 

![image](https://user-images.githubusercontent.com/19910999/31246815-a01a1cf0-a9dc-11e7-8463-829a0cf26fd7.png)

Can an option to do this be added?

**Comment by bernhard-da** [comment] 2017-10-05 18:54
yeah, I was just trying this. Just need to find a way to suppress the warnings ...

will update shortly...

**Comment by bernhard-da** [comment] 2017-10-05 19:33
hi @molfe797 could you try again using the chagnes i committed with 7fbb999812559ece504560c4a924c559c4f18239 ?

**Comment by molfe797** [comment] 2017-10-05 20:26
Yes! It works great.

![image](https://user-images.githubusercontent.com/19910999/31250785-f192eb36-a9e9-11e7-8f20-f55c4ef4e9cf.png)

**Comment by bernhard-da** [comment] 2017-10-06 06:09
@molfe797 great!

**Closed by bernhard-da** 2017-10-06 06:09 UTC
